# Generated by Django 2.2.12 on 2020-06-29 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webtest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webcasestep',
            old_name='Webcase',
            new_name='webcase',
        ),
        migrations.RenameField(
            model_name='webcasestep',
            old_name='Webevelement',
            new_name='webevelement',
        ),
        migrations.RenameField(
            model_name='webcasestep',
            old_name='Webfindmethod',
            new_name='webfindmethod',
        ),
        migrations.RenameField(
            model_name='webcasestep',
            old_name='Webtestobjname',
            new_name='webtestobjname',
        ),
        migrations.RenameField(
            model_name='webcasestep',
            old_name='Webteststep',
            new_name='webteststep',
        ),
    ]
