# Generated by Django 2.2.12 on 2020-05-29 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bug',
            old_name='bugcreate',
            new_name='bugcreater',
        ),
        migrations.RenameField(
            model_name='bug',
            old_name='bug_level',
            new_name='buglevel',
        ),
    ]
