# Generated by Django 2.2.12 on 2020-07-20 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0002_apis'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apistep',
            options={'verbose_name': '流程场景接口测试用例', 'verbose_name_plural': '流程场景接口测试用例'},
        ),
    ]
